### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Miha-ha** [gdm85/wolfengo#6]
mkdir -p bin .gopath
if [ ! -L .gopath/src ]; then ln -s "..../wolfengo/vendor" .gopath/src; fi
cd src && GOBIN="../bin/" GOPATH="..../wolfengo/.gopath" go install && mv ../bin/src ../bin/wolfengo
cannot install, GOBIN must be an absolute path
make: **\* [build] Error 1

**Comment by gdm85** [comment]
@Miha-ha fixed in current master, thanks for reporting!
