### ISSUE TITLE
separated render thread and Logic update

### ISSUE THREAD

**Issue by heat** [gdm85/wolfengo#7]
Hi,

Should we use separate threads to run our logic updates and render game.

> Https://github.com/gdm85/wolfengo/blob/master/src/main.go#L175

Maybe refactor using GO channels, and so on. How could we rewrite this piece of code to achieve that?

**Comment by gdm85** [comment]
Sorry for the late reply @heat; yes, ideally only the OpenGL part would run on the pinned thread, while the rest outside.

I do not reckon it as an important change though since the game logic is so simple.

**Comment by gdm85** [comment]
I checked this a bit further: in Go you do not have threads, so there is no guarantee that the goroutine you use to lock GL operations is not the same as the main goroutine.

Additionally, nothing would be gained by moving all GL operations in their own goroutine (the non-rendering parts of the game are trivial) and for sure it would make it more difficult to read for newcomers, so I am closing this.
